### PR TITLE
upgrade agent-base to 4.2

### PR DESCRIPTION
**Pull request by tareqhs**
propagate ``agent-base`` fix https://github.com/TooTallNate/node-agent-base/pull/18

### CODE REVIEW

**Comment by tareqhs** [comment]
@TooTallNate restored the PR, please approve

**Comment by silverwind** [comment]
ping @TooTallNate

**Comment by TooTallNate** [comment]
This isn't _strictly_ required due to the `^` in the semver version. But thank you, merging!

**Comment by silverwind** [comment]
Indeed. Was just wondering why this fix hasn't propagated to npm yet, but looks `pacote` is the blocker here.

**Pull request merged**
