### PR TITLE
Revert "Meh…"

### PR DESCRIPTION
**Pull request by lpinca**
This reverts commit 2590f76d6a1a39391ef7dd5046d2132bcd85ff61 as per https://github.com/TooTallNate/node-https-proxy-agent/commit/2590f76d6a1a39391ef7dd5046d2132bcd85ff61#commitcomment-35365193

### CODE REVIEW

**Comment by TooTallNate** [comment]
The reason that I did that commit was because (on macOS, at least, but apparently not Linux) the "after all" hooks were timing out (the `proxy` and `sslProxy` never emit a "close" event).

If you would like to dig deeper into why macOS is timing out that would be appreciated.

**Comment by lpinca** [comment]
Hmm I'm on macOS (10.14.6) and I see no issues. I'll add it to Travis.

**Comment by lpinca** [comment]
There are some failing tests on macOS but no timeouts. It seems something is written to the socket after being destroyed by the other peer.

**Comment by TooTallNate** [comment]
The tests failing seems to be intermittent. And indeed it's working properly for me now on macOS. Not sure what the issue for me was last night.

**Comment by lpinca** [comment]
I think the failing tests are due to an `'error'` listener removed too soon but I'm not sure if here or the `proxy` dependency.

**Comment by lpinca** [comment]
I investigated a little and it seems tests flakiness on macOS is caused by the premature removal of the `'error'` listener on the client socket done by the proxy server on this line https://github.com/TooTallNate/proxy/blob/1.0.0/proxy.js#L319. `socket.end()` sometimes raises an error ('read ECONNRESET').

Interestingly the error is only emitted when using an HTTPS proxy **and** the target is an HTTPS endpoint but I did not figure out why.

**Comment by lpinca** [comment]
I've opened https://github.com/TooTallNate/proxy/pull/16.

**Pull request merged**
